### ISSUE TITLE
EDMC does not recongnise the new plugin 2.0

### ISSUE THREAD

**Issue by Ark4di** [NoFoolLikeOne/EDMC-USS-Survey#4]
Titel says it. I deleted 1.0 and extracted the 2.0 folder - restarted EDMC several times - but the plugin does not load.

**Comment by NoFoolLikeOne** [comment]
The plugin doesn't display anything until you hit update or jump to the first system. Can you check?

**Comment by Ark4di** [comment]
Checking. The plugin will not show. Also in preferences/plugin it does not show with the active pulgins. 
Something's wrong with my setup maybe. First version did show as active and also in the UI. But I had problem with 1.0 too - it did not send data to the google spreadsheet.

**Comment by NoFoolLikeOne** [comment]
Can you find the EDMC log file. It may give some clues.

I suspect that the reason it doesnt work is because your connection to google is blocked somehow.

**Comment by NoFoolLikeOne** [comment]
C:\Users\**YOURNAME**\AppData\Local\temp\EDMarketConnector.log

**Comment by Assimilator1** [comment]
Same problem here, log - 
E:D Market Connector 2.4.4.0 2017-10-16T00:15:19
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"

I noticed your plugin .py & pyo files are in the USS survey folder, is that right?

**Comment by Assimilator1** [comment]
No change copying them to EDMCs root......

**Comment by Assimilator1** [comment]
Ok the problem is you have a folder within a folder, so when you extract it to the EDMC>plugins folder your not extracting the files in their but the 2 folder with the files, & it seems EDMC can't read that.

**Comment by Ark4di** [comment]
Log:

E:D Market Connector 2.4.4.0 2017-10-15T20:11:12
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
plugin EDMC-Alien-Tour-1.1 disabled
loading plugin EDMC-Screenshot-1.6 from "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-1.6\load.py"
[..]
Screenshot loaded!
loading plugin EDMC-USS-Survey-2.0 from "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py"
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:2: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:3: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:4: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:5: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:6: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:7: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:8: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:9: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:10: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:11: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:13: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:14: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:15: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:16: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
Traceback (most recent call last):
  File "plug.pyo", line 135, in load_plugins
  File "plug.pyo", line 46, in __init__
  File "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py", line 71, in plugin_start
  File "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py", line 32, in get_patrol
  File "requests\api.pyo", line 71, in get
  File "requests\api.pyo", line 57, in request
  File "requests\sessions.pyo", line 475, in request
  File "requests\sessions.pyo", line 585, in send
  File "requests\adapters.pyo", line 477, in send
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by NoFoolLikeOne** [comment]
Could you try renaming EDMC-USS-Survey-2.0 to EDMC-USS-Survey

**Comment by Ark4di** [comment]
Renaming did not solve the issue. I also tried to rename 2.0 to 1.0 - since 1.0 at least showed in the program.

EDMC-USS-Survey-1.0 is recognised by EDMC. It shows in the tab for active plug-ins. 2.0 does not. It's strange.

**Comment by NoFoolLikeOne** [comment]
2.0 downloads a Google sheet in plugin_start and this is failing with an SSL certificate error. 1.0 doesnt do this so it fails later on when attempting to access the google forms.

I don't understand why it would fail for your PC and not mine.

**Comment by NoFoolLikeOne** [comment]
Can you try replacing your load.py with this one?

https://raw.githubusercontent.com/NoFoolLikeOne/EDMC-USS-Survey/SSL-Cert-Problem/load.py

**Comment by Ark4di** [comment]
I did replace the load.py, now the plugin works perfectly for me. You are genius! Thx : )

**Comment by Assimilator1** [comment]
How come mine didn't work until I had the files directly in the plugin folder?

**Comment by NoFoolLikeOne** [comment]
@Assimilator1 

The files should be here
C:\Users\YOURNAME\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey

eg

C:\Users\YOURNAME\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py

**Comment by Assimilator1** [comment]
Apart from it said survey-2.0, they were, but it didn't work there, I moved the files directly into the plugin folder & now it works (patrol showing after updating, but not tested in game yet)

**Comment by NoFoolLikeOne** [comment]
It should be in the sub folder but rename it so it doesn't have 2.0. 

I've raised that as an issue with EDMC

**Comment by Assimilator1** [comment]
Shut EDMC off, tried that, didn't work ,only placing the files directly in the plugins folder seems to work (EDMC showing 'Patrol' section).

**Comment by NoFoolLikeOne** [comment]
The real problem here is the installation instructions. 

They need updating along these lines https://github.com/Marginal/EDMarketConnector/wiki/Plugins

**Comment by NoFoolLikeOne** [comment]
In latest beta version
